baseurl = "https://phills.me.uk/"
title = "Phill Sparks"
languageCode = "en-GB"
theme = "phills"
enableRobotsTxt = true
enableGitInfo = true
pygmentsUseClasses = true

[outputFormats]
  [outputFormats.NetlifyRedirects]
    name = "_Redirects"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "_Redirects"]

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "association"
  weight = 1

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.speakerDeck]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Params]
  Author = "Phill Sparks"
  Description = "Climbing Training • Instruction • Coaching"
  Twitter = "@SparksPhill"
  Facebook = "sparks.phill"

  [Params.Redirects]
    Gone = [
      "/bookmarks",
      "/changelog",
      "/comments",
      "/directory",
      "/fortune",
      "/login",
      "/mods",
      "/register",
      "/users"
    ]

    [Params.Redirects.Custom]
      "/association/*" = "/associations/:splat"
      "/blog/:year/:month/:date/:slug" = "/post/:slug/"
      "/blog/tag/*" = "/tags/:splat/"
      "/experience/*" = "/experience//"
      "/pb/*" = "/snip/:splat/"
      "/snips/*" = "/snip/:splat/"


[[menu.social]]
  name = "Facebook"
  identifier = "facebook"
  url = "https://www.facebook.com/phills.climbing"

[[menu.social]]
  name = "GitHub"
  identifier = "github"
  url = "https://github.com/sparksp/"

[[menu.social]]
  name = "Instagram"
  identifier = "instagram"
  url = "https://www.instagram.com/sparksphill/"

[[menu.social]]
  name = "Twitter"
  identifier = "twitter"
  url = "https://twitter.com/SparksPhill"