baseurl = "https://phills.me.uk/"
title = "Phill Sparks"
languageCode = "en-GB"
theme = "phills"
enableRobotsTxt = true
enableGitInfo = true
pygmentsUseClasses = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.speakerDeck]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Params]
  Author = "Phill Sparks"
  Twitter = "@SparksPhill"
  Facebook = "sparks.phill"

[[menu.social]]
  name = "Facebook"
  identifier = "facebook"
  url = "https://www.facebook.com/sparks.phill"

[[menu.social]]
  name = "GitHub"
  identifier = "github"
  url = "https://github.com/sparksp/"

[[menu.social]]
  name = "Instagram"
  identifier = "instagram"
  url = "https://www.instagram.com/sparksphill/"

[[menu.social]]
  name = "Twitter"
  identifier = "twitter"
  url = "https://twitter.com/SparksPhill"