baseurl = "https://phills.me.uk/"

theme = [
  "LovePhill",
  "LoveIt",
]

title = "Phill Sparks"

languageCode = "en-GB"
languageName = "English"

enableRobotsTxt = true
enableGitInfo = true
pygmentsUseClasses = false

[author]
  name = "Phill Sparks"
  email = "hello@phills.me.uk"
  link = "https://phills.me.uk"

[Params]
  Author = "Phill Sparks"
  Description = "Climbing Training • Instruction • Coaching"
  fingerprint = "sha512"
  gitRepo = "https://github.com/sparksp/phills.me.uk"

  [Params.header.title]
    name = "Phill Sparks"

  [Params.footer]
    since = 2016
    hugo = false
    custom = """
Hosted on <a href="//netlify.com/">Netlify</a> | 
Powered by <a href="//gohugo.io/">Hugo</a> | 
Theme - <a href="//github.com/dillonzq/LoveIt"><i class="far fa-kiss-wink-heart fa-fw" aria-hidden="true"></i> LoveIt</a>
"""

  [Params.app]
    title = "Phill Sparks"
    iconColor = "#da532c"
    themeColor = "#da532c"
    tileColor = "#da532c"

  [Params.social]
    GitHub = "sparksp"
    Facebook = "phills.climbing"
    Instagram = "sparksphill"
    Twitter = "SparksPhill"
    Email = "hello@phills.me.uk?subject=Course+Enquiry"

  [Params.home.profile]
    enable = true
    avatarURL = "/about/phills.jpg"
    subtitle = "Climbing Training • Instruction • Coaching"
    typeit = false

  [Params.home.posts]
    enable = false

  [Params.search]
    enable = true

  [Params.Redirects]
    Gone = [
      "/bookmarks",
      "/changelog",
      "/comments",
      "/directory",
      "/fortune",
      "/login",
      "/mods",
      "/register",
      "/users"
    ]

    [Params.Redirects.Custom]
      "/association/*" = "/associations/:splat"
      "/blog/:year/:month/:date/:slug" = "/posts/:slug"
      "/blog/tag/*" = "/tags/:splat"
      "/course/*" = "/courses/:splat"
      "/experience/*" = "/experience//"
      "/pb/*" = "/snip/:splat"
      "/photo/*" = "/photos/:splat"
      "/policy/*" = "/policies/:splat"
      "/post/*" = "/posts/:splat"
      "/snip/*" = "/posts/:splat"
      "/snips/*" = "/snip/:splat"

[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

  [markup.goldmark.parser.attribute]
    block = true
    title = true

[outputFormats]
  [outputFormats.NetlifyRedirects]
    name = "_Redirects"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "JSON", "_Redirects"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.speakerDeck]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[related]
  threshold = 80
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "association"
    weight = 1
