---
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  snip:
    default_front_matter_template: snip
  post:
    default_front_matter_template: post
  experience:
    default_front_matter_template: experience
version: 0.31.1
