# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Phill Sparks"
license = "MIT"
licenselink = "https://github.com/sparksp/phills.me.uk/blob/master/LICENSE.md"
description = ""
homepage = "http://phills.me.uk/"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = "Phill Sparks"
  homepage = "http://phills.me.uk/"
