name = "Phill's Theme"
license = "MIT"
licenselink = "https://github.com/sparksp/phills.me.uk/blob/master/themes/phills/LICENSE.md"
description = "Theme for my website"
homepage = "https://phills.me.uk/"
tags = ["personal", "cv"]
features = []
min_version = 0.24

[author]
    name = "Phill Sparks"
    homepage = "https://phills.me.uk/"
